openapi: 3.1.0
info:
  title: Flat Finder REST API
  version: 0.1.0

paths:
  /api/v1/listings/accommodation:
    get:
      summary: Get a list of accommodation listings, optionally filtered and sorted
      parameters:
        - name: location
          in: query
          required: true
          description: Location to search for nearby accommodation
          schema:
            type: string
        - name: radius
          in: query
          required: true
          description: Maximum search radius from location
          schema:
            type: number
        - name: max_price
          in: query
          required: false
          description: Maximum monthly price of accomodations
          schema:
            type: number
        - name: sources
          in: query
          required: false
          description: >-
            Comma-separated list of sources to fetch listings from. If not
            provided, searches in all available sources in the country of the
            searched location
          schema:
            type: array
            items:
              type: string
          explode: false
        - name: sort_by
          in: query
          required: false
          description: >-
            How listings should be sorted in the search results. Affects which
            page listings appear on. If not provided, the listings are not
            sorted by most recent first
          schema:
            type: string
            enum:
              - newest
              - cheapest
              - closest
        - name: page
          in: query
          required: false
          description: >-
            Zero-based index of the page of the search results. If not provided,
            the first page is returned. Should use the same size parameter when
            retrieving subsequent pages to get continuous results.
          schema:
            type: integer
            minimum: 0
        - name: size
          in: query
          required: false
          description: The number of listings to return in the search results.
          schema:
            type: integer
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - distance
                    - isFavourite
                    - accomodation
                  properties:
                    distance:
                      type: number
                      description: Distance in km from search location
                    isFavourite:
                      type: boolean
                      description: Does the listing exist in the user's favourites
                    accomodation:
                      type: object
                      required:
                        - title
                        - shortDescription
                        - thumbnailUrl
                        - accomodationType
                        - numberOfRooms
                        - source
                        - price
                        - postCode
                      properties:
                        title:
                          type: string
                        shortDescription:
                          type: string
                        thumbnailUrl:
                          type: string
                        accomodationType:
                          type: string
                        numberOfRooms:
                          type: integer
                        source:
                          type: string
                        price:
                          type: number
                        postCode:
                          type: string

  /api/v1/listings/seeking:
    get:
      summary: Get a list of seeking listings
