name: push-to-qmul-gh

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Push to QMUL GitHub
        run: |
          git remote add upstream "https://${{ secrets.QMUL_GH_PAT }}@${{ vars.QMUL_GH_URL }}"
          git push upstream main
