name: Validate OpenAPI spec

on:
  push:
    branches:
      - main
    paths:
      - "backend/openapi.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/openapi.yaml"

jobs:
  validate_openapi:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote

    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: backend/openapi.yaml
